export const SENDIT_API_ORIGIN = 'https://sendit.infiniteappsai.com';
export const SENDIT_API_BASE_URL = `${SENDIT_API_ORIGIN}/api/v1`;

export const PLATFORM_OPTIONS = [
  { name: 'X (Twitter)', value: 'x' },
  { name: 'LinkedIn', value: 'linkedin' },
  { name: 'LinkedIn Page', value: 'linkedin-page' },
  { name: 'Facebook', value: 'facebook' },
  { name: 'Instagram', value: 'instagram' },
  { name: 'Instagram Standalone', value: 'instagram-standalone' },
  { name: 'Threads', value: 'threads' },
  { name: 'Bluesky', value: 'bluesky' },
  { name: 'Mastodon', value: 'mastodon' },
  { name: 'Warpcast', value: 'warpcast' },
  { name: 'Nostr', value: 'nostr' },
  { name: 'VK', value: 'vk' },
  { name: 'YouTube', value: 'youtube' },
  { name: 'TikTok', value: 'tiktok' },
  { name: 'Reddit', value: 'reddit' },
  { name: 'Lemmy', value: 'lemmy' },
  { name: 'Discord', value: 'discord' },
  { name: 'Slack', value: 'slack' },
  { name: 'Telegram', value: 'telegram' },
  { name: 'Pinterest', value: 'pinterest' },
  { name: 'Dribbble', value: 'dribbble' },
  { name: 'Medium', value: 'medium' },
  { name: 'DEV.to', value: 'devto' },
  { name: 'Hashnode', value: 'hashnode' },
  { name: 'WordPress', value: 'wordpress' },
  { name: 'Google My Business', value: 'gmb' },
  { name: 'Listmonk', value: 'listmonk' },
  { name: 'Skool', value: 'skool' },
  { name: 'Whop', value: 'whop' },
  { name: 'Kick', value: 'kick' },
  { name: 'Twitch', value: 'twitch' },
  { name: 'Product Hunt', value: 'producthunt' },
];
